### ISSUE TITLE
Unlocking the 500 results limit

### ISSUE THREAD

**Issue by ofisurr** [itchylol742/FimarchiveSearchGUI#3]
I know it's set to avoid lag, but there seems to be no option to change it anyways. Would like to remove every story associated with a specific tag. Not possible?

**Comment by itchylol742** [comment]
Right now it's hard coded as 500, but I might let the user change that in the future. If you use it from a Java IDE and compile and run it yourself, you can go into FimArchiveSearchGUI.java and change maxNumberOfResultsShown to some large number like 999999. If you're using the .jar version, there's no easy way to fix it.

**Comment by itchylol742** [comment]
New update has checkbox to toggle limit
